title: Thoughtwire Magazine
name: Thoughtwire Magazine
description: >-
  Essays, notes, and dispatches on markets, tech, and everything in between.
baseurl: ""
url: "https://thoughtwiremagazine.me"

remote_theme: wowthemesnet/mediumish-theme-jekyll

logo: 'assets/images/logo_2_cropped.png'

instagram: "https://instagram.com/thoughtwire.magazine"
email: "thoughtwiremagazine@gmail.com"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6
paginate_path: /page:num/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
